CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
email VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
description VARCHAR NOT NULL,
available BOOLEAN NOT NULL,
user_id BIGINT NOT NULL,
CONSTRAINT fk_items_owner FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
id SERIAL PRIMARY KEY,
text VARCHAR NOT NULL,
item_id BIGINT NOT NULL,
author_name VARCHAR NOT NULL,
created TIMESTAMP NOT NULL,
CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking (
id SERIAL PRIMARY KEY,
item_id BIGINT,
user_id BIGINT,
status VARCHAR(255) CHECK (
status IN ('WAITING', 'APPROVED', 'REJECTED', 'ALL', 'PAST', 'CURRENT', 'FUTURE')),
start_time TIMESTAMP,
end_time TIMESTAMP,
CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
